# Generated by Django 4.0.1 on 2022-02-03 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_alter_post_img_commentpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostUser',
        ),
    ]
